"""add second_email, preffered_lang, make password_hash nullable

Revision ID: 5235973741ff
Revises: 551f64bc8d02
Create Date: 2025-11-23 23:08:58.615115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5235973741ff'
down_revision: Union[str, Sequence[str], None] = '551f64bc8d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preffered_lang', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['second_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'preffered_lang')
    op.drop_column('users', 'second_email')
    # ### end Alembic commands ###
